import Link from "next/link";
import { festivals } from "@danyeo-ori/constants";
import { FestivalCard } from "../components/festival-card";
import { PreRegistrationForm } from "../components/pre-registration-form";

const services = [["🎮", "미니게임", "/games"], ["🎪", "전국 축제", "/festivals"], ["📅", "축제 달력", "/calendar"], ["💬", "현장 후기", "/community"], ["🧭", "여행 코스", "/festivals"], ["🪙", "마일리지", "/games"], ["🗺️", "축제 지도", "/festivals"], ["🎟️", "내 티켓", "/#pre-register"]] as const;

export default function HomePage() {
  return <main><section className="hero"><div className="container"><div className="hero-strip"><article className="hero-card side"><div className="scene scene-water" /><div className="hero-content"><span className="kicker white">COOL FESTIVAL</span><h2>계곡으로 떠나는<br />한여름 축제</h2></div></article><article className="hero-card"><div className="scene scene-night" /><div className="hero-content"><span className="kicker lime">이번 주 추천</span><h2>축제를 보기 전에,<br />먼저 플레이해 보세요.</h2><p>전국 축제의 대표 프로그램을 짧은 미니게임으로 체험하고 방문 혜택을 모아요.</p><Link className="primary-btn light-btn" href="/games">게임 둘러보기</Link></div><span className="slide-count">1 / 8　Ⅱ</span></article><article className="hero-card side"><div className="scene scene-corn" /><div className="hero-content"><span className="kicker white">LOCAL TASTE</span><h2>홍천 찰옥수수<br />미리 먹기</h2></div></article></div></div></section>
  <section className="section pt-0"><div className="container"><h2 className="service-title">완벽한 축제 준비를 위한 다녀오리 서비스</h2><div className="service-row">{services.map(([icon, label, href]) => <Link className="service-item" href={href} key={label}><span className="service-icon">{icon}</span>{label}</Link>)}</div></div></section>
  <section className="section section-soft"><div className="container"><div className="section-head"><div><span className="eyebrow">Explore festival</span><h2>이번 여름, 많이 찾는 축제</h2><p>축제 정보와 미니게임을 한 카드에서 확인하세요.</p></div><Link className="outline-btn" href="/festivals">전국 축제 전체보기 →</Link></div><div className="festival-grid">{festivals.slice(0, 6).map((festival) => <FestivalCard festival={festival} key={festival.id} />)}</div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">How it works</span><h2>축제를 만나는 새로운 순서</h2></div></div><div className="game-grid">{[["fish", "🔎", "STEP 01", "내 취향 축제 발견", "지역, 시기, 테마를 선택해 이번 주말에 갈 축제를 찾습니다."], ["corn", "🎮", "STEP 02", "대표 프로그램 플레이", "축제의 핵심 체험을 10–30초 미니게임으로 먼저 경험합니다."], ["chicken", "🎁", "STEP 03", "혜택 받고 현장 방문", "게임 결과에 따라 마일리지와 현장 사용 혜택을 확인합니다."]].map(([cover, icon, step, title, description]) => <article className="game-card" key={step}><div className={`game-cover ${cover}`}><span className="game-icon">{icon}</span></div><div className="game-body"><span className="kicker">{step}</span><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section><PreRegistrationForm /></main>;
}
