"use client";

import { FormEvent, useState } from "react";
import { initialPosts } from "@danyeo-ori/constants";
import type { CommunityPost } from "@danyeo-ori/types";

const tabs = ["전체", "공지", "현장후기", "질문", "게임"] as const;
export function CommunityBoard() {
  const [posts, setPosts] = useState(initialPosts); const [tab, setTab] = useState<(typeof tabs)[number]>("전체"); const [message, setMessage] = useState("");
  const visiblePosts = tab === "전체" ? posts : posts.filter((post) => post.category === tab);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const festival = String(data.get("festival")); const title = String(data.get("title")).trim(); const content = String(data.get("content")).trim(); if (!festival || !title || !content) { setMessage("축제 태그, 제목, 내용을 모두 입력해 주세요."); return; } const post: CommunityPost = { id: Date.now(), festival, category: "현장후기", title, author: "새 축제러", time: "방금", views: 0 }; setPosts([post, ...posts]); event.currentTarget.reset(); setMessage("게시글이 목록 상단에 등록됐어요. MVP에서는 브라우저를 새로고침하면 초기화됩니다."); }
  return <section><div className="container community-layout"><div><div className="board-head"><div className="channel-cover"><div className="channel-icon">💬</div><div><h2>전국 축제 정보 채널</h2><p>가격, 주차, 혼잡도, 먹거리와 미니게임 후기를 공유해 주세요.</p></div></div><div className="board-tools"><div className="board-tabs">{tabs.map((item) => <button type="button" onClick={() => setTab(item)} className={tab === item ? "active" : ""} key={item}>{item}</button>)}</div><span className="chip">축제 태그 필수</span></div></div><div className="post-table"><div className="post-table-inner"><div className="post-row header"><div>번호</div><div>축제 태그</div><div>제목</div><div>작성자</div><div>시간</div><div>조회</div></div>{visiblePosts.map((post) => <div className="post-row" key={post.id}><div className="post-no">{post.id}</div><div><span className={`board-tag ${post.category === "현장후기" ? "review" : post.category === "질문" ? "question" : ""}`}>{post.festival}</span></div><div className="post-title">{post.title}</div><div className="post-author">{post.author}</div><div className="post-time">{post.time}</div><div className="post-views">{post.views}</div></div>)}</div></div><div id="write" className="write-box"><div className="section-head compact"><div><span className="eyebrow">Write post</span><h2>새 게시글 작성</h2></div><span className="meta">* 축제 태그 필수</span></div><form onSubmit={submit}><div className="form-grid"><select className="control" name="festival" defaultValue=""><option value="" disabled>축제 태그를 선택하세요 *</option><option>보령머드축제</option><option>화천 산천어축제</option><option>장수 쿨밸리 페스티벌</option><option>홍천 찰옥수수 축제</option></select><input className="control" name="title" placeholder="제목을 입력하세요" /></div><textarea className="control post-content" name="content" placeholder="가격, 혼잡도, 주차, 게임, 먹거리 등 도움이 되는 정보를 작성해 주세요." /><div className="form-actions"><button type="submit" className="primary-btn">게시글 등록</button></div>{message && <p className="form-message" role="status">{message}</p>}</form></div></div><aside className="side-stack"><div className="side-card"><h3>지금 많이 보는 축제</h3><ol className="rank-list">{["보령머드축제", "장수 쿨밸리 페스티벌", "서울썸머비치", "홍천 찰옥수수 축제", "봉화은어축제"].map((festival) => <li key={festival}>{festival}</li>)}</ol></div><div className="side-card"><h3>게시판 이용 원칙</h3><p className="meta">축제 태그는 필수이며, 가격·광고·리워드 정보는 사실 확인이 가능한 내용으로 작성해 주세요.</p><div className="chip-row"><span className="chip">#가격정보</span><span className="chip">#주차</span><span className="chip">#혼잡도</span><span className="chip">#게임후기</span></div></div></aside></div></section>;
}
